/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type WarmupGet200Response,
    WarmupGet200ResponseFromJSON,
    WarmupGet200ResponseToJSON,
} from '../models/WarmupGet200Response';

/**
 * 
 */
export class MaintenanceApi extends runtime.BaseAPI {

    /**
     * Creates request options for warmupGet without sending the request
     */
    async warmupGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warmup`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Prisma クライアントウォームアップ
     */
    async warmupGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WarmupGet200Response>> {
        const requestOptions = await this.warmupGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WarmupGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Prisma クライアントウォームアップ
     */
    async warmupGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WarmupGet200Response> {
        const response = await this.warmupGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for warmupHead without sending the request
     */
    async warmupHeadRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warmup`;

        return {
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ヘルスチェック
     */
    async warmupHeadRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.warmupHeadRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ヘルスチェック
     */
    async warmupHead(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.warmupHeadRaw(initOverrides);
    }

}
