/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type NotifyPost200Response,
    NotifyPost200ResponseFromJSON,
    NotifyPost200ResponseToJSON,
} from '../models/NotifyPost200Response';
import {
    type NotifyPostRequest,
    NotifyPostRequestFromJSON,
    NotifyPostRequestToJSON,
} from '../models/NotifyPostRequest';

export interface NotifyPostOperationRequest {
    notifyPostRequest: NotifyPostRequest;
}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for notifyPost without sending the request
     */
    async notifyPostRequestOpts(requestParameters: NotifyPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notifyPostRequest'] == null) {
            throw new runtime.RequiredError(
                'notifyPostRequest',
                'Required parameter "notifyPostRequest" was null or undefined when calling notifyPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/notify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotifyPostRequestToJSON(requestParameters['notifyPostRequest']),
        };
    }

    /**
     * 入退室イベントを Discord Webhook に投稿します。
     * Discord 通知送信
     */
    async notifyPostRaw(requestParameters: NotifyPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotifyPost200Response>> {
        const requestOptions = await this.notifyPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotifyPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 入退室イベントを Discord Webhook に投稿します。
     * Discord 通知送信
     */
    async notifyPost(requestParameters: NotifyPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotifyPost200Response> {
        const response = await this.notifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
