/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type Office,
    OfficeFromJSON,
    OfficeToJSON,
} from '../models/Office';

/**
 * 
 */
export class OfficesApi extends runtime.BaseAPI {

    /**
     * Creates request options for officesGet without sending the request
     */
    async officesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/offices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * オフィス一覧の取得
     */
    async officesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Office>>> {
        const requestOptions = await this.officesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OfficeFromJSON));
    }

    /**
     * オフィス一覧の取得
     */
    async officesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Office>> {
        const response = await this.officesGetRaw(initOverrides);
        return await response.value();
    }

}
