/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type MessageResponse,
    MessageResponseFromJSON,
    MessageResponseToJSON,
} from '../models/MessageResponse';
import {
    type UserDetail,
    UserDetailFromJSON,
    UserDetailToJSON,
} from '../models/UserDetail';
import {
    type UserListItem,
    UserListItemFromJSON,
    UserListItemToJSON,
} from '../models/UserListItem';
import {
    type UserWithOffice,
    UserWithOfficeFromJSON,
    UserWithOfficeToJSON,
} from '../models/UserWithOffice';
import {
    type UsersIdPatchRequest,
    UsersIdPatchRequestFromJSON,
    UsersIdPatchRequestToJSON,
} from '../models/UsersIdPatchRequest';
import {
    type UsersLoginPost200Response,
    UsersLoginPost200ResponseFromJSON,
    UsersLoginPost200ResponseToJSON,
} from '../models/UsersLoginPost200Response';
import {
    type UsersLoginPostRequest,
    UsersLoginPostRequestFromJSON,
    UsersLoginPostRequestToJSON,
} from '../models/UsersLoginPostRequest';
import {
    type UsersMeGet200Response,
    UsersMeGet200ResponseFromJSON,
    UsersMeGet200ResponseToJSON,
} from '../models/UsersMeGet200Response';
import {
    type UsersResetPasswordRequestPostRequest,
    UsersResetPasswordRequestPostRequestFromJSON,
    UsersResetPasswordRequestPostRequestToJSON,
} from '../models/UsersResetPasswordRequestPostRequest';
import {
    type UsersResetPasswordTokenPostRequest,
    UsersResetPasswordTokenPostRequestFromJSON,
    UsersResetPasswordTokenPostRequestToJSON,
} from '../models/UsersResetPasswordTokenPostRequest';

export interface UsersGetRequest {
    officeCode?: string;
}

export interface UsersIdDeleteRequest {
    id: number;
}

export interface UsersIdGetRequest {
    id: number;
}

export interface UsersIdPatchOperationRequest {
    id: number;
    usersIdPatchRequest: UsersIdPatchRequest;
}

export interface UsersLoginPostOperationRequest {
    usersLoginPostRequest: UsersLoginPostRequest;
}

export interface UsersPostRequest {
    name: string;
    email: string;
    password: string;
    icon: Blob;
    officeCode: string;
}

export interface UsersResetPasswordRequestPostOperationRequest {
    usersResetPasswordRequestPostRequest: UsersResetPasswordRequestPostRequest;
}

export interface UsersResetPasswordTokenPostOperationRequest {
    token: string;
    usersResetPasswordTokenPostRequest: UsersResetPasswordTokenPostRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for usersGet without sending the request
     */
    async usersGetRequestOpts(requestParameters: UsersGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['officeCode'] != null) {
            queryParameters['officeCode'] = requestParameters['officeCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 登録フォームなどで利用するためのユーザー一覧を返します。`officeCode` を指定した場合は該当オフィスのユーザーのみに絞り込みます。
     * ユーザー一覧の取得
     */
    async usersGetRaw(requestParameters: UsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserListItem>>> {
        const requestOptions = await this.usersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserListItemFromJSON));
    }

    /**
     * 登録フォームなどで利用するためのユーザー一覧を返します。`officeCode` を指定した場合は該当オフィスのユーザーのみに絞り込みます。
     * ユーザー一覧の取得
     */
    async usersGet(requestParameters: UsersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserListItem>> {
        const response = await this.usersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdDelete without sending the request
     */
    async usersIdDeleteRequestOpts(requestParameters: UsersIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザー削除
     */
    async usersIdDeleteRaw(requestParameters: UsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const requestOptions = await this.usersIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * ユーザー削除
     */
    async usersIdDelete(requestParameters: UsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.usersIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdGet without sending the request
     */
    async usersIdGetRequestOpts(requestParameters: UsersIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ユーザー詳細の取得
     */
    async usersIdGetRaw(requestParameters: UsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetail>> {
        const requestOptions = await this.usersIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailFromJSON(jsonValue));
    }

    /**
     * ユーザー詳細の取得
     */
    async usersIdGet(requestParameters: UsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetail> {
        const response = await this.usersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdPatch without sending the request
     */
    async usersIdPatchRequestOpts(requestParameters: UsersIdPatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdPatch().'
            );
        }

        if (requestParameters['usersIdPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'usersIdPatchRequest',
                'Required parameter "usersIdPatchRequest" was null or undefined when calling usersIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UsersIdPatchRequestToJSON(requestParameters['usersIdPatchRequest']),
        };
    }

    /**
     * ユーザーノートの更新
     */
    async usersIdPatchRaw(requestParameters: UsersIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetail>> {
        const requestOptions = await this.usersIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailFromJSON(jsonValue));
    }

    /**
     * ユーザーノートの更新
     */
    async usersIdPatch(requestParameters: UsersIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetail> {
        const response = await this.usersIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersLoginPost without sending the request
     */
    async usersLoginPostRequestOpts(requestParameters: UsersLoginPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['usersLoginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'usersLoginPostRequest',
                'Required parameter "usersLoginPostRequest" was null or undefined when calling usersLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersLoginPostRequestToJSON(requestParameters['usersLoginPostRequest']),
        };
    }

    /**
     * ログイン
     */
    async usersLoginPostRaw(requestParameters: UsersLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersLoginPost200Response>> {
        const requestOptions = await this.usersLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * ログイン
     */
    async usersLoginPost(requestParameters: UsersLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersLoginPost200Response> {
        const response = await this.usersLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersMeGet without sending the request
     */
    async usersMeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 認証済みユーザー情報
     */
    async usersMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersMeGet200Response>> {
        const requestOptions = await this.usersMeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersMeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 認証済みユーザー情報
     */
    async usersMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersMeGet200Response> {
        const response = await this.usersMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersPost without sending the request
     */
    async usersPostRequestOpts(requestParameters: UsersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling usersPost().'
            );
        }

        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling usersPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling usersPost().'
            );
        }

        if (requestParameters['icon'] == null) {
            throw new runtime.RequiredError(
                'icon',
                'Required parameter "icon" was null or undefined when calling usersPost().'
            );
        }

        if (requestParameters['officeCode'] == null) {
            throw new runtime.RequiredError(
                'officeCode',
                'Required parameter "officeCode" was null or undefined when calling usersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['email'] != null) {
            formParams.append('email', requestParameters['email'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['icon'] != null) {
            formParams.append('icon', requestParameters['icon'] as any);
        }

        if (requestParameters['officeCode'] != null) {
            formParams.append('officeCode', requestParameters['officeCode'] as any);
        }


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * フォームデータを受け取り、プロフィール画像をアップロードした上でユーザーを作成します。
     * ユーザー新規登録
     */
    async usersPostRaw(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserWithOffice>> {
        const requestOptions = await this.usersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserWithOfficeFromJSON(jsonValue));
    }

    /**
     * フォームデータを受け取り、プロフィール画像をアップロードした上でユーザーを作成します。
     * ユーザー新規登録
     */
    async usersPost(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserWithOffice> {
        const response = await this.usersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersResetPasswordRequestPost without sending the request
     */
    async usersResetPasswordRequestPostRequestOpts(requestParameters: UsersResetPasswordRequestPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['usersResetPasswordRequestPostRequest'] == null) {
            throw new runtime.RequiredError(
                'usersResetPasswordRequestPostRequest',
                'Required parameter "usersResetPasswordRequestPostRequest" was null or undefined when calling usersResetPasswordRequestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/reset-password-request`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersResetPasswordRequestPostRequestToJSON(requestParameters['usersResetPasswordRequestPostRequest']),
        };
    }

    /**
     * パスワードリセット申請
     */
    async usersResetPasswordRequestPostRaw(requestParameters: UsersResetPasswordRequestPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const requestOptions = await this.usersResetPasswordRequestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * パスワードリセット申請
     */
    async usersResetPasswordRequestPost(requestParameters: UsersResetPasswordRequestPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.usersResetPasswordRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersResetPasswordTokenPost without sending the request
     */
    async usersResetPasswordTokenPostRequestOpts(requestParameters: UsersResetPasswordTokenPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling usersResetPasswordTokenPost().'
            );
        }

        if (requestParameters['usersResetPasswordTokenPostRequest'] == null) {
            throw new runtime.RequiredError(
                'usersResetPasswordTokenPostRequest',
                'Required parameter "usersResetPasswordTokenPostRequest" was null or undefined when calling usersResetPasswordTokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/reset-password/{token}`;
        urlPath = urlPath.replace('{token}', encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersResetPasswordTokenPostRequestToJSON(requestParameters['usersResetPasswordTokenPostRequest']),
        };
    }

    /**
     * パスワードリセット実行
     */
    async usersResetPasswordTokenPostRaw(requestParameters: UsersResetPasswordTokenPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const requestOptions = await this.usersResetPasswordTokenPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * パスワードリセット実行
     */
    async usersResetPasswordTokenPost(requestParameters: UsersResetPasswordTokenPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.usersResetPasswordTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
