/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotifyPostRequest
 */
export interface NotifyPostRequest {
    /**
     * 対象ユーザー名
     * @type {string}
     * @memberof NotifyPostRequest
     */
    user: string;
    /**
     * 「入室」または「退室」などのステータス文字列
     * @type {string}
     * @memberof NotifyPostRequest
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof NotifyPostRequest
     */
    officeCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotifyPostRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the NotifyPostRequest interface.
 */
export function instanceOfNotifyPostRequest(value: object): value is NotifyPostRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function NotifyPostRequestFromJSON(json: any): NotifyPostRequest {
    return NotifyPostRequestFromJSONTyped(json, false);
}

export function NotifyPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotifyPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'],
        'status': json['status'],
        'officeCode': json['officeCode'] == null ? undefined : json['officeCode'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function NotifyPostRequestToJSON(json: any): NotifyPostRequest {
    return NotifyPostRequestToJSONTyped(json, false);
}

export function NotifyPostRequestToJSONTyped(value?: NotifyPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'status': value['status'],
        'officeCode': value['officeCode'],
        'note': value['note'],
    };
}

