/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Office
 */
export interface Office {
    /**
     * 
     * @type {number}
     * @memberof Office
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Office
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof Office
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Office
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof Office
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof Office
     */
    radiusMeters: number;
}

/**
 * Check if a given object implements the Office interface.
 */
export function instanceOfOffice(value: object): value is Office {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('radiusMeters' in value) || value['radiusMeters'] === undefined) return false;
    return true;
}

export function OfficeFromJSON(json: any): Office {
    return OfficeFromJSONTyped(json, false);
}

export function OfficeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Office {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'radiusMeters': json['radiusMeters'],
    };
}

export function OfficeToJSON(json: any): Office {
    return OfficeToJSONTyped(json, false);
}

export function OfficeToJSONTyped(value?: Office | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'radiusMeters': value['radiusMeters'],
    };
}

