/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersLoginPostRequest
 */
export interface UsersLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersLoginPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UsersLoginPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UsersLoginPostRequest interface.
 */
export function instanceOfUsersLoginPostRequest(value: object): value is UsersLoginPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UsersLoginPostRequestFromJSON(json: any): UsersLoginPostRequest {
    return UsersLoginPostRequestFromJSONTyped(json, false);
}

export function UsersLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function UsersLoginPostRequestToJSON(json: any): UsersLoginPostRequest {
    return UsersLoginPostRequestToJSONTyped(json, false);
}

export function UsersLoginPostRequestToJSONTyped(value?: UsersLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

