/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Office } from './Office';
import {
    OfficeFromJSON,
    OfficeFromJSONTyped,
    OfficeToJSON,
    OfficeToJSONTyped,
} from './Office';

/**
 * 
 * @export
 * @interface UserListItem
 */
export interface UserListItem {
    /**
     * 
     * @type {number}
     * @memberof UserListItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserListItem
     */
    iconFileName: string;
    /**
     * 
     * @type {Office}
     * @memberof UserListItem
     */
    office?: Office | null;
}

/**
 * Check if a given object implements the UserListItem interface.
 */
export function instanceOfUserListItem(value: object): value is UserListItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('iconFileName' in value) || value['iconFileName'] === undefined) return false;
    return true;
}

export function UserListItemFromJSON(json: any): UserListItem {
    return UserListItemFromJSONTyped(json, false);
}

export function UserListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'iconFileName': json['iconFileName'],
        'office': json['office'] == null ? undefined : OfficeFromJSON(json['office']),
    };
}

export function UserListItemToJSON(json: any): UserListItem {
    return UserListItemToJSONTyped(json, false);
}

export function UserListItemToJSONTyped(value?: UserListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'iconFileName': value['iconFileName'],
        'office': OfficeToJSON(value['office']),
    };
}

