/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersIdPatchRequest
 */
export interface UsersIdPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersIdPatchRequest
     */
    note: string | null;
}

/**
 * Check if a given object implements the UsersIdPatchRequest interface.
 */
export function instanceOfUsersIdPatchRequest(value: object): value is UsersIdPatchRequest {
    if (!('note' in value) || value['note'] === undefined) return false;
    return true;
}

export function UsersIdPatchRequestFromJSON(json: any): UsersIdPatchRequest {
    return UsersIdPatchRequestFromJSONTyped(json, false);
}

export function UsersIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'],
    };
}

export function UsersIdPatchRequestToJSON(json: any): UsersIdPatchRequest {
    return UsersIdPatchRequestToJSONTyped(json, false);
}

export function UsersIdPatchRequestToJSONTyped(value?: UsersIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
    };
}

