/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Office } from './Office';
import {
    OfficeFromJSON,
    OfficeFromJSONTyped,
    OfficeToJSON,
    OfficeToJSONTyped,
} from './Office';

/**
 * 
 * @export
 * @interface UserWithOffice
 */
export interface UserWithOffice {
    /**
     * 
     * @type {number}
     * @memberof UserWithOffice
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserWithOffice
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithOffice
     */
    email: string;
    /**
     * 公開URL
     * @type {string}
     * @memberof UserWithOffice
     */
    iconFileName: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithOffice
     */
    note?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserWithOffice
     */
    entered?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserWithOffice
     */
    enteredAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserWithOffice
     */
    exitedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UserWithOffice
     */
    officeId: number;
    /**
     * 
     * @type {Office}
     * @memberof UserWithOffice
     */
    office: Office;
}

/**
 * Check if a given object implements the UserWithOffice interface.
 */
export function instanceOfUserWithOffice(value: object): value is UserWithOffice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('iconFileName' in value) || value['iconFileName'] === undefined) return false;
    if (!('officeId' in value) || value['officeId'] === undefined) return false;
    if (!('office' in value) || value['office'] === undefined) return false;
    return true;
}

export function UserWithOfficeFromJSON(json: any): UserWithOffice {
    return UserWithOfficeFromJSONTyped(json, false);
}

export function UserWithOfficeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithOffice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'iconFileName': json['iconFileName'],
        'note': json['note'] == null ? undefined : json['note'],
        'entered': json['entered'] == null ? undefined : json['entered'],
        'enteredAt': json['enteredAt'] == null ? undefined : (new Date(json['enteredAt'])),
        'exitedAt': json['exitedAt'] == null ? undefined : (new Date(json['exitedAt'])),
        'officeId': json['officeId'],
        'office': OfficeFromJSON(json['office']),
    };
}

export function UserWithOfficeToJSON(json: any): UserWithOffice {
    return UserWithOfficeToJSONTyped(json, false);
}

export function UserWithOfficeToJSONTyped(value?: UserWithOffice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'iconFileName': value['iconFileName'],
        'note': value['note'],
        'entered': value['entered'],
        'enteredAt': value['enteredAt'] == null ? value['enteredAt'] : value['enteredAt'].toISOString(),
        'exitedAt': value['exitedAt'] == null ? value['exitedAt'] : value['exitedAt'].toISOString(),
        'officeId': value['officeId'],
        'office': OfficeToJSON(value['office']),
    };
}

