/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnteredUser } from './EnteredUser';
import {
    EnteredUserFromJSON,
    EnteredUserFromJSONTyped,
    EnteredUserToJSON,
    EnteredUserToJSONTyped,
} from './EnteredUser';
import type { UserSafe } from './UserSafe';
import {
    UserSafeFromJSON,
    UserSafeFromJSONTyped,
    UserSafeToJSON,
    UserSafeToJSONTyped,
} from './UserSafe';

/**
 * 
 * @export
 * @interface UsersMeGet200Response
 */
export interface UsersMeGet200Response {
    /**
     * 
     * @type {UserSafe}
     * @memberof UsersMeGet200Response
     */
    user: UserSafe;
    /**
     * 
     * @type {Array<EnteredUser>}
     * @memberof UsersMeGet200Response
     */
    enteredUsers: Array<EnteredUser>;
}

/**
 * Check if a given object implements the UsersMeGet200Response interface.
 */
export function instanceOfUsersMeGet200Response(value: object): value is UsersMeGet200Response {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('enteredUsers' in value) || value['enteredUsers'] === undefined) return false;
    return true;
}

export function UsersMeGet200ResponseFromJSON(json: any): UsersMeGet200Response {
    return UsersMeGet200ResponseFromJSONTyped(json, false);
}

export function UsersMeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserSafeFromJSON(json['user']),
        'enteredUsers': ((json['enteredUsers'] as Array<any>).map(EnteredUserFromJSON)),
    };
}

export function UsersMeGet200ResponseToJSON(json: any): UsersMeGet200Response {
    return UsersMeGet200ResponseToJSONTyped(json, false);
}

export function UsersMeGet200ResponseToJSONTyped(value?: UsersMeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserSafeToJSON(value['user']),
        'enteredUsers': ((value['enteredUsers'] as Array<any>).map(EnteredUserToJSON)),
    };
}

