/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersResetPasswordTokenPostRequest
 */
export interface UsersResetPasswordTokenPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersResetPasswordTokenPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UsersResetPasswordTokenPostRequest interface.
 */
export function instanceOfUsersResetPasswordTokenPostRequest(value: object): value is UsersResetPasswordTokenPostRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UsersResetPasswordTokenPostRequestFromJSON(json: any): UsersResetPasswordTokenPostRequest {
    return UsersResetPasswordTokenPostRequestFromJSONTyped(json, false);
}

export function UsersResetPasswordTokenPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersResetPasswordTokenPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function UsersResetPasswordTokenPostRequestToJSON(json: any): UsersResetPasswordTokenPostRequest {
    return UsersResetPasswordTokenPostRequestToJSONTyped(json, false);
}

export function UsersResetPasswordTokenPostRequestToJSONTyped(value?: UsersResetPasswordTokenPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

