/* tslint:disable */
/* eslint-disable */
/**
 * Office Manager API
 * Web とモバイルクライアントから共通で利用する Office Manager バックエンド API の OpenAPI 仕様です。 仕様は開発中であり、今後変更される可能性があります。 
 *
 * The version of the OpenAPI document: 7.7.2
 * Contact: dev@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WarmupGet200Response
 */
export interface WarmupGet200Response {
    /**
     * 
     * @type {string}
     * @memberof WarmupGet200Response
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof WarmupGet200Response
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the WarmupGet200Response interface.
 */
export function instanceOfWarmupGet200Response(value: object): value is WarmupGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function WarmupGet200ResponseFromJSON(json: any): WarmupGet200Response {
    return WarmupGet200ResponseFromJSONTyped(json, false);
}

export function WarmupGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WarmupGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function WarmupGet200ResponseToJSON(json: any): WarmupGet200Response {
    return WarmupGet200ResponseToJSONTyped(json, false);
}

export function WarmupGet200ResponseToJSONTyped(value?: WarmupGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'].toISOString(),
    };
}

